import type { SiteCardProps } from "@/types";

export const siteData: SiteCardProps[] = [
	{
		title: "ENDLER.DEV",
		tags: ["個人ブログ", "Rust"],
		href: "https://endler.dev/",
		lang: "en",
	},
	{
		title: "Gojabako Zone",
		href: "https://gojabako.zone/",
		tags: ["個人ブログ", "React"],
		lang: "ja",
	},
	{
		title: "naopoyo",
		href: "https://naopoyo.com/",
		tags: ["個人ブログ", "React"],
		lang: "ja",
	},
	{
		title: "GIOSUE SULIPANO",
		href: "https://giosuesulipano.com/",
		tags: ["個人ブログ"],
		lang: "en",
	},
	{
		title: "Takuya Matsumoto",
		href: "https://www.craftz.dog/",
		tags: ["個人ブログ", "個人開発", "React Native"],
		lang: "en",
	},
	{
		title: "Tania Rascia",
		href: "https://www.taniarascia.com",
		tags: ["個人ブログ", "JavaScript", "チュートリアル", "Web開発"],
		lang: "en",
	},
	{
		title: "Overreacted",
		href: "https://overreacted.io/",
		tags: ["個人ブログ", "React", "Dan Abramov", "JavaScript"],
		lang: "en",
	},
	{
		title: "Josh W. Comeau",
		href: "https://www.joshwcomeau.com/",
		tags: ["個人ブログ", "React", "CSS", "アニメーション", "Web開発"],
		lang: "en",
	},
	{
		title: "Kent C. Dodds",
		href: "https://kentcdodds.com/",
		tags: ["個人ブログ", "React", "JavaScript", "テスト", "教育"],
		lang: "en",
	},
	{
		title: "Rivea River",
		href: "https://rivea0.github.io/",
		tags: ["個人ブログ", "JavaScript", "Python", "プログラミング"],
		lang: "en",
	},
	{
		title: "Yuya Kinoshita",
		href: "https://yuyakinoshita.com",
		tags: ["個人ブログ", "タイポグラフィ", "デザイン"],
		lang: "na",
	},
	{
		title: "Yoshinori Kinoshita",
		href: "https://www.yoshinoki.dev/",
		tags: ["個人ブログ", "Web開発", "プログラミング"],
		lang: "ja",
	},
	{
		title: "Azuki Azusa",
		href: "https://azukiazusa.dev/",
		tags: ["個人ブログ", "フロントエンド", "Vue", "JavaScript"],
		lang: "ja",
	},
	{
		title: "Darek Kay",
		href: "https://darekkay.com/",
		tags: ["個人ブログ", "Web開発", "アクセシビリティ", "オープンソース"],
		lang: "en",
	},
	{
		title: "potato4d",
		href: "https://d.potato4d.me/",
		tags: ["個人ブログ", "Vue", "JavaScript", "フロントエンド"],
		lang: "ja",
	},
	{
		title: "PR1V4T3",
		href: "https://www.pr1v4t3.io",
		tags: ["個人ブログ", "TypeScript"],
		lang: "ja",
	},
	{
		title: "Oikawa Dev",
		href: "https://oikawa.dev/blog",
		tags: ["個人ブログ", "プログラミング", "Web開発"],
		lang: "ja",
	},
	{
		title: "Kevin Langley Jr",
		href: "https://kevinlangleyjr.dev/",
		tags: ["個人ブログ", "Web開発", "JavaScript"],
		lang: "en",
	},
	{
		title: "Yi Xtian",
		href: "https://www.yixtian.com/",
		tags: ["個人ブログ", "Web開発", "デザイン"],
		lang: "en",
	},
	{
		title: "Jatin Sharma",
		href: "https://j471n.in",
		tags: ["個人ブログ", "Web開発", "プログラミング", "フロントエンド"],
		lang: "en",
	},
	{
		title: "Ian Mitchell",
		href: "https://ianmitchell.dev",
		tags: ["個人ブログ", "Web開発", "JavaScript", "プログラミング"],
		lang: "en",
	},
	{
		title: "Peter Lunch",
		href: "https://www.peterlunch.com/",
		tags: ["個人ブログ", "Web開発", "デザイン"],
		lang: "en",
	},
	{
		title: "T28 Dev",
		href: "https://t28.dev/",
		tags: ["個人ブログ", "プログラミング", "Web開発"],
		lang: "ja",
	},
	{
		title: "Koh Dev",
		href: "https://blog.koh.dev/",
		tags: ["個人ブログ", "プログラミング", "Web開発"],
		lang: "ja",
	},
	{
		title: "Tech Shed",
		href: "https://techshed.runbookdocs.com",
		tags: ["技術ドキュメント", "プログラミング", "Web開発", "チュートリアル"],
		lang: "en",
	},
	{
		title: "osgsm.io",
		href: "https://osgsm.io/",
		tags: ["個人ブログ", "プログラミング", "Web開発"],
		lang: "ja",
	},
	{
		title: "おじさんブログ",
		href: "https://blog.ojisan.io/",
		tags: ["個人ブログ", "JavaScript", "フロントエンド", "React"],
		lang: "ja",
	},
	{
		title: "h6i.org",
		href: "https://h6i.org/",
		tags: ["個人ブログ", "プログラミング", "Web開発"],
		lang: "ja",
	},
	{
		title: "Sandyman Dev",
		href: "https://www.sandyman.dev/",
		tags: ["個人ブログ", "プログラミング", "Web開発"],
		lang: "en",
	},
	{
		title: "Lee Robinson Substack",
		href: "https://leerob.substack.com/",
		tags: ["ニュースレター", "Web開発", "フロントエンド", "Vercel"],
		lang: "en",
	},
	{
		title: "Lee Robinson",
		href: "https://leerob.com/",
		tags: ["個人ブログ", "Next.js", "React", "Vercel", "Web開発"],
		lang: "en",
	},
	{
		title: "Ben Adam",
		href: "https://benadam.me/",
		tags: ["個人ブログ", "Web開発", "プログラミング"],
		lang: "en",
	},
	{
		title: "Naoki Otsu",
		href: "https://naokiotsu.com/blog/",
		tags: ["個人ブログ", "デザイン", "Web開発"],
		lang: "ja",
	},
	{
		title: "Belong Inc. Dev",
		href: "https://belonginc.dev/",
		tags: ["企業ブログ", "技術ブログ", "Web開発", "プログラミング"],
		lang: "ja",
	},
	{
		title: "Eiji Page",
		href: "https://eiji.page/",
		tags: ["個人ブログ", "プログラミング", "Web開発"],
		lang: "ja",
	},
	{
		title: "Kitty Giraudel",
		href: "https://kittygiraudel.com/blog/",
		tags: ["個人ブログ", "CSS", "アクセシビリティ", "JavaScript"],
		lang: "en",
	},
	{
		title: "Minerva",
		href: "https://minerva.mamansoft.net",
		tags: ["Wiki", "ナレッジベース", "プログラミング"],
		lang: "ja",
	},
	{
		title: "One of One Dev",
		href: "https://oneofone.dev/",
		tags: ["個人ブログ", "プログラミング", "Web開発"],
		lang: "en",
	},
	{
		title: "Kenoss Github",
		href: "https://kenoss.github.io/",
		tags: ["個人ブログ", "プログラミング", "オープンソース"],
		lang: "ja",
	},
	{
		title: "Worthe-it",
		href: "https://www.worthe-it.co.za",
		tags: ["個人ブログ", "プログラミング", "ソフトウェア開発"],
		lang: "en",
	},
	{
		title: "Laurie Tratt",
		href: "https://tratt.net/laurie/",
		tags: [
			"個人ブログ",
			"プログラミング言語",
			"コンピュータサイエンス",
			"研究",
		],
		lang: "en",
	},
	{
		title: "Binary Fish",
		href: "https://binary-fish.vercel.app/",
		tags: ["個人ブログ", "プログラミング", "Web開発"],
		lang: "en",
	},
	{
		title: "Daiki Portfolio Blog",
		href: "https://blog.daiki-portfolio.com/",
		tags: ["個人ブログ", "ポートフォリオ", "Web開発"],
		lang: "ja",
	},
	{
		title: "yuku.dev",
		href: "https://yuku.dev/",
		tags: ["個人ブログ", "プログラミング", "Web開発"],
		lang: "ja",
	},
	{
		title: "Spanish Forest",
		href: "https://records.dodgson.org/",
		tags: ["個人ブログ", "プログラミング", "Web開発"],
		lang: "ja",
	},
];
